### ISSUE TITLE
Dead ?

### ISSUE THREAD

**Issue by pfteter** [ZanichelliEditore/storybook-addon-stencil#7]
Is this project deprecated ?

stencil is at version 2 but now we are at version 4 so it wont install

**Comment by valadas** [comment]
I know I never managed to make it work right, would love to but we are using lit (only for storybook) in order to have semi-jsx/tsx support to display stencil components, we did it here: https://github.com/DNNCommunity/dnn-elements/tree/develop/packages/stencil-library

**Comment by pfteter** [comment]
Migrate to:

https://github.com/stencil-community/unplugin-stencil/tree/main

one of the core devs is working on it

stencil integration for variouse builders

**Comment by valadas** [comment]
@pfteter do you have an example usage of this with a storybook context?

**Comment by pfteter** [comment]
Have no time but it can be easily done the vite compiler configuration can be exposed in storybook and a plugin can be injected.
see:
https://storybook.js.org/docs/builders/vite#configuration

**Comment by DarioSacco** [comment]
Hi, we recently released the version `0.2.1` where we upgraded both Stencil to v4 and Storybook to v8 and moved to Vite.

**Comment by valadas** [comment]
That is awesome @DarioSacco thanks so much, I'll give it a try next week...
